name: Employee CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          python -m unittest discover || true

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.saurav2402 }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.saurav2402 }}/employee-app:${{ github.sha }} .
          docker tag ${{ secrets.saurav2402 }}/employee-app:${{ github.sha }} \
                     ${{ secrets.saurav2402 }}/employee-app:latest

      - name: Push Image
        run: |
          docker push ${{ secrets.saurav2402 }}/employee-app:${{ github.sha }}
          docker push ${{ secrets.saurav2402 }}/employee-app:latest
